package flyjob

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"
)

type OracleDialect struct{}

func (d *OracleDialect) EnsureSchema(ctx context.Context, conn *sql.Conn, jobsTable, attemptsTable string) error {
	upperJobs := strings.ToUpper(jobsTable)
	upperAttempts := strings.ToUpper(attemptsTable)

	plsql := fmt.Sprintf(`
		DECLARE
			tbl_count NUMBER;
			idx_count NUMBER;
		BEGIN
			SELECT COUNT(*) INTO tbl_count FROM user_tables WHERE table_name = '%s';
			IF tbl_count = 0 THEN
				EXECUTE IMMEDIATE 'CREATE TABLE "%s" (
					id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					queue         VARCHAR2(100) DEFAULT ''default'' NOT NULL,
					action        VARCHAR2(100) NOT NULL,
					payload       CLOB DEFAULT ''{}'' NOT NULL,
					status        VARCHAR2(20) DEFAULT ''pending'' NOT NULL,
					attempts      NUMBER(10) DEFAULT 0 NOT NULL,
					max_attempts  NUMBER(10) DEFAULT 3 NOT NULL,
					error_message CLOB,
					run_at        TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
					started_at    TIMESTAMP WITH TIME ZONE,
					completed_at  TIMESTAMP WITH TIME ZONE,
					created_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
					updated_at    TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
				)';
			END IF;

			SELECT COUNT(*) INTO idx_count FROM user_indexes WHERE index_name = 'IDX_%s_PEND';
			IF idx_count = 0 THEN
				EXECUTE IMMEDIATE 'CREATE INDEX "IDX_%s_PEND" ON "%s"(queue, status, run_at)';
			END IF;

			SELECT COUNT(*) INTO idx_count FROM user_indexes WHERE index_name = 'IDX_%s_ACT';
			IF idx_count = 0 THEN
				EXECUTE IMMEDIATE 'CREATE INDEX "IDX_%s_ACT" ON "%s"(action)';
			END IF;

			SELECT COUNT(*) INTO tbl_count FROM user_tables WHERE table_name = '%s';
			IF tbl_count = 0 THEN
				EXECUTE IMMEDIATE 'CREATE TABLE "%s" (
					id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
					job_id         NUMBER(19) NOT NULL,
					attempt_number NUMBER(10) NOT NULL,
					status         VARCHAR2(20) NOT NULL,
					error_message  CLOB,
					ran_at         TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
					CONSTRAINT fk_%s_job_id FOREIGN KEY (job_id) REFERENCES "%s"(id) ON DELETE CASCADE
				)';
			END IF;

			SELECT COUNT(*) INTO idx_count FROM user_indexes WHERE index_name = 'IDX_%s_JOB';
			IF idx_count = 0 THEN
				EXECUTE IMMEDIATE 'CREATE INDEX "IDX_%s_JOB" ON "%s"(job_id)';
			END IF;
		END;
	`, upperJobs, upperJobs, upperJobs, upperJobs, upperJobs, upperJobs, upperJobs, upperJobs, upperAttempts, upperAttempts, upperAttempts, upperJobs, upperAttempts, upperAttempts, upperAttempts)

	_, err := conn.ExecContext(ctx, plsql)
	if err != nil {
		return fmt.Errorf("oracle/ensure_schema: %w", err)
	}
	return nil
}

func (d *OracleDialect) InsertJobSQL(jobsTable string) string {
	upperJobs := strings.ToUpper(jobsTable)
	return fmt.Sprintf(`
		INSERT INTO "%s" (
			queue, action, payload, status, attempts, max_attempts, 
			error_message, run_at, started_at, completed_at, created_at, updated_at
		) VALUES (:1, :2, :3, 'pending', 0, 3, NULL, CURRENT_TIMESTAMP, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
	`, upperJobs)
}

func (d *OracleDialect) FetchPendingJobs(ctx context.Context, db *sql.DB, jobsTable string, queues []string, limit int) ([]Job, error) {
	upperJobs := strings.ToUpper(jobsTable)
	if len(queues) == 0 {
		queues = []string{"default"}
	}

	placeholders := make([]string, len(queues))
	args := make([]any, len(queues))
	for i, q := range queues {
		placeholders[i] = fmt.Sprintf(":%d", i+1)
		args[i] = q
	}

	selectQuery := fmt.Sprintf(`
		SELECT id FROM "%s"
		WHERE status = 'pending' AND queue IN (%s) AND run_at <= CURRENT_TIMESTAMP
		ORDER BY id ASC
		FETCH FIRST :limit ROWS ONLY
		FOR UPDATE SKIP LOCKED
	`, upperJobs, strings.Join(placeholders, ", "))

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return nil, fmt.Errorf("oracle/fetch_pending: failed to begin tx: %w", err)
	}
	defer tx.Rollback()

	selectArgs := append(args, limit)
	rows, err := tx.QueryContext(ctx, selectQuery, selectArgs...)
	if err != nil {
		return nil, fmt.Errorf("oracle/fetch_pending/select: %w", err)
	}

	var ids []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			return nil, fmt.Errorf("oracle/fetch_pending/scan_id: %w", err)
		}
		ids = append(ids, id)
	}
	rows.Close()

	if len(ids) == 0 {
		return nil, nil
	}

	idPlaceholders := make([]string, len(ids))
	updateArgs := make([]any, len(ids))
	for i, id := range ids {
		idPlaceholders[i] = fmt.Sprintf(":%d", i+1)
		updateArgs[i] = id
	}

	updateQuery := fmt.Sprintf(`
		UPDATE "%s"
		SET status = 'processing', started_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP, attempts = attempts + 1
		WHERE id IN (%s)
	`, upperJobs, strings.Join(idPlaceholders, ", "))

	_, err = tx.ExecContext(ctx, updateQuery, updateArgs...)
	if err != nil {
		return nil, fmt.Errorf("oracle/fetch_pending/update: %w", err)
	}

	fetchQuery := fmt.Sprintf(`
		SELECT id, queue, action, payload, status, attempts, max_attempts, error_message, run_at, started_at, completed_at, created_at, updated_at
		FROM "%s"
		WHERE id IN (%s)
	`, upperJobs, strings.Join(idPlaceholders, ", "))

	rowsDetail, err := tx.QueryContext(ctx, fetchQuery, updateArgs...)
	if err != nil {
		return nil, fmt.Errorf("oracle/fetch_pending/fetch_details: %w", err)
	}
	defer rowsDetail.Close()

	var jobs []Job
	for rowsDetail.Next() {
		var j Job
		err := rowsDetail.Scan(
			&j.ID, &j.Queue, &j.Action, &j.Payload, &j.Status, &j.Attempts, &j.MaxAttempts,
			&j.ErrorMessage, &j.RunAt, &j.StartedAt, &j.CompletedAt, &j.CreatedAt, &j.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("oracle/fetch_pending/scan_job: %w", err)
		}
		jobs = append(jobs, j)
	}

	if err := tx.Commit(); err != nil {
		return nil, fmt.Errorf("oracle/fetch_pending/commit: %w", err)
	}

	return jobs, nil
}

func (d *OracleDialect) MarkCompleted(ctx context.Context, db *sql.DB, jobsTable, attemptsTable string, job Job) error {
	upperJobs := strings.ToUpper(jobsTable)
	upperAttempts := strings.ToUpper(attemptsTable)

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("oracle/completed: %w", err)
	}
	defer tx.Rollback()

	queryJob := fmt.Sprintf(`
		UPDATE "%s"
		SET status = 'completed', completed_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
		WHERE id = :1
	`, upperJobs)
	_, err = tx.ExecContext(ctx, queryJob, job.ID)
	if err != nil {
		return fmt.Errorf("oracle/completed/job: %w", err)
	}

	queryAttempt := fmt.Sprintf(`
		INSERT INTO "%s" (job_id, attempt_number, status, error_message, ran_at)
		VALUES (:1, :2, 'completed', NULL, CURRENT_TIMESTAMP)
	`, upperAttempts)
	_, err = tx.ExecContext(ctx, queryAttempt, job.ID, job.Attempts)
	if err != nil {
		return fmt.Errorf("oracle/completed/attempt: %w", err)
	}

	return tx.Commit()
}

func (d *OracleDialect) MarkFailed(ctx context.Context, db *sql.DB, jobsTable, attemptsTable string, job Job, errMsg string) error {
	upperJobs := strings.ToUpper(jobsTable)
	upperAttempts := strings.ToUpper(attemptsTable)

	status := "pending"
	runAt := time.Now().Add(time.Duration(job.Attempts) * 2 * time.Minute)
	if job.Attempts >= job.MaxAttempts {
		status = "failed"
	}

	tx, err := db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("oracle/failed: %w", err)
	}
	defer tx.Rollback()

	queryJob := fmt.Sprintf(`
		UPDATE "%s"
		SET status = :1, error_message = :2, run_at = :3, updated_at = CURRENT_TIMESTAMP
		WHERE id = :4
	`, upperJobs)
	_, err = tx.ExecContext(ctx, queryJob, status, errMsg, runAt, job.ID)
	if err != nil {
		return fmt.Errorf("oracle/failed/job: %w", err)
	}

	queryAttempt := fmt.Sprintf(`
		INSERT INTO "%s" (job_id, attempt_number, status, error_message, ran_at)
		VALUES (:1, :2, :3, :4, CURRENT_TIMESTAMP)
	`, upperAttempts)
	_, err = tx.ExecContext(ctx, queryAttempt, job.ID, job.Attempts, status, errMsg)
	if err != nil {
		return fmt.Errorf("oracle/failed/attempt: %w", err)
	}

	return tx.Commit()
}
